---
# flag to enable/disable the debug generation
debug: false

# execution type (descriptor, clustering or metric)
executionType: descriptor

##### execution types #####
# descriptor calculation execution params 
descriptor:
    targetPoint: 4185

    patchSize: 0.02
    normalRadius: -1
    bandNumber: 8
    bandWidth: 0.005
    bidirectional: false
    useProjection: false

    sequenceBin: 0.005
    sequenceStat: mean # mean or median

# clustering execution params
clustering:
    generateElbowCurve: false
    generateDistanceMatrix: false

    labelData: true
    centersLocation: ./input/centers_30_7.dat

    # params used only when no labeling is done
    implementation: custom # opencv, custom or stochastic
    metric: closest # closest or euclidean
    clusters: 5
    maxIterations: 10
    stopThreshold: 0.000001
    attempts: 5
    cacheLocation: ./cache/
    useConfidence: false # use confidence when the metric allows it

# metric testcase evaluation params
metric:
    targetMetric: closest # closest or euclidean
    metricArgs: 4 false # arguments passed to the metric

##### cloud smoothing params #####
cloudSmoothing:
    type: gaussian # gaussian or mls

    gaussian:
        sigma: 4
        radius: 0.005

    mls:
        radius: 0.05

##### Synthetic cloud generation params #####
syntheticClouds:
    generateCloud: false
    type: cube # cube, cylinder, sphere, half_sphere, plane
...